### ISSUE TITLE
cannot import name 'TDClient' from 'td.client'

### ISSUE THREAD

**Issue by iomega15** [areed1192/td-ameritrade-api#7]
Hello, I am having the following issue when I run the example from GIT:

runfile('C:/Users/iomega15/Desktop/td_example/using_td_library_git.py', wdir='C:/Users/iomega15/Desktop/td_example')
Reloaded modules: config, iomega15
Traceback (most recent call last):

  File "C:\Users\iomega15\Desktop\td_example\using_td_library_git.py", line 25, in <module>
    client_id = config.get('main', 'client_id')

  File "C:\Users\iomega15\anaconda3\lib\configparser.py", line 781, in get
    d = self._unify_values(section, vars)

  File "C:\Users\iomega15\anaconda3\lib\configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None

NoSectionError: No section: 'main'

runfile('C:/Users/iomega15/Desktop/td_example/using_td_library.py', wdir='C:/Users/iomega15/Desktop/td_example')
Traceback (most recent call last):

  File "C:\Users\iomega15\Desktop\td_example\using_td_library.py", line 15, in <module>
    from td.client import TDClient

ImportError: cannot import name 'TDClient' from 'td.client' (C:\Users\iomega15\anaconda3\Lib\site-packages\td\client.py)

I have also tried running it the [youtube video](https://www.youtube.com/watch?v=8N1IxYXs4e8&list=PLMFiyl9zyN5TPRs6k-IWUfOMUkN2x8_we&index=7&t=1196s) way, but I get this issue:

ImportError: cannot import name 'TDClient' from 'td.client' (C:\Users\iomega15\anaconda3\Lib\site-packages\td\client.py)

I saw in the comments that it was a bug in the older version, but that was like a year ago and I just installed/updated the latest (as far as I can tell) from github:  Successfully installed td-ameritrade-python-api-0.3.5

Though, I am a bit confused what the actual latest version is, because the github website says:
![image](https://user-images.githubusercontent.com/5264699/154830433-4c37e87f-4c98-47da-9273-d006d41b5ec2.png)

And in your youtube comments from a year ago you mentioned upgrading to 0.2.8 to eliminate this issue...

**Comment by granthooks** [comment]
There are 2 projects. 
td-ameritrade-python-api
td-ameritrade-api

It looks like td-ameritrade-python-api (which was v0.3.5) was sunset and now @areed1192 has been working on td-ameritrade-api (v0.1.1)  
**Thank you for the great/useful module Alex!**

Your Issue here is the same underlying problem as in this Discussion (td module not recognized)
https://github.com/areed1192/td-ameritrade-api/discussions/9
Hoping for some community input to get this working.

**Comment by platypushunter** [comment]
I agree with granthooks above, theres the two different projects, and they are named differently. it might have been better for him to create a new release/branch/fork of the other one to avoid confusion, but hindsight is 20/20. Regardless this issue is just from importing the wrong API. If you want to use the old one (which is still up, for now, but could be overwritten at any point now) use `pip3 install td-ameritrade-python-api` However i would suggest learning to use this module, as he appears to still support it.

**Comment by platypushunter** [comment]
I think there may be an issue somewhere that's not letting pip install the `client.py` `credentials.py` and `session.py` scripts which is weird

However if you install it as editable by cloning this repo, and from within the root of the repo doing `pip install -e .` it should work. This is either a bug/error or intentional because the project isn't quite done yet.

**Comment by platypushunter** [comment]
The most recent merge/commit #[837315d](https://github.com/areed1192/td-ameritrade-api/commit/837315db9f80da2c2eb581ccd955007365521fe7) has fixed this.

**Comment by akshaygulabrao** [comment]
Make sure **td-ameritrade-python-api** is uninstalled with
`pip uninstall td-ameritrade-python-api`.

This fixed the issue for me.
